Threshold = 95
DisplayMonitorSources = true
EnableUpdates = true
GuiltTripped = true
FilterInput = true
FilterOutput = true
LastUsedInput = "alsa_input.pci-0000_08_00.6.analog-stereo"
LastUsedOutput = "alsa_output.pci-0000_08_00.6.analog-stereo"
