Threshold = 75
DisplayMonitorSources = true
EnableUpdates = true
GuiltTripped = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_output.pci-0000_09_00.4.analog-surround-21.monitor"
LastUsedOutput = ""
